"""Emit the paper's measured tables straight from results/*.json.

No number in Section 5 is typed by hand.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, ".")
OUT = Path("../tables")
OUT.mkdir(exist_ok=True)

LV = {0: r"\Vzero", 1: r"\Vone", 2: r"\Vtwo", 3: r"\Vthree", 4: r"\Vfour"}
ORDER = ["v0-none", "v1-merkle", "v1-chain", "v2-ed25519", "v2-bls",
         "v3-manifest", "v3-policy-sample", "v4-raw", "v4-attested", "partial-homomac"]
SHORT = {
    "v0-none": "no evidence",
    "v1-merkle": "anchored Merkle root",
    "v1-chain": "anchored hash chain",
    "v2-ed25519": "per-record signatures",
    "v2-bls": "aggregate signature",
    "v3-manifest": "manifest sent in full",
    "v3-policy-sample": "20 policy-position openings",
    "v4-raw": "ship raw and recompute",
    "v4-attested": "attested report\\,$^{\\ddagger}$",
    "partial-homomac": "aggregate MAC\\,$^{\\dagger}$",
}
PROF = {"rho_soft": r"$\rho_{\mathrm{s}}$", "rho_iso": r"$\rho_{\mathrm{i}}$",
        "rho_eval": r"$\rho_{\mathrm{e}}$"}
AB = {"hash": "H", "sign": "S", "verify": "V", "agg": "A", "pairing": "P",
      "mul": "M", "fuse": "F"}


def si(x):
    return f"{int(x):,}".replace(",", r"\,")


def counts(d):
    parts = [f"{si(d[k])}{AB[k]}" for k in AB if d.get(k)]
    return " ".join(parts) if parts else "---"


def mem(b):
    return "---" if b == 0 else (f"{b}" if b < 1024 else f"{b/1024:.1f}k")


def mempair(p, j):
    return f"{mem(p)}/{mem(j)}"


def cost_table(data, sn):
    n = data["headline_n"]
    mkt = {r["stack"]: r for r in data["operators"]["mkt"][str(n)]}
    mean = {r["stack"]: r for r in data["operators"]["mean"][str(n)]}
    cir = {(r["circuit"], r["n"]): r for r in sn["results"]}
    raw = mkt["v4-raw"]["B_ev"]
    ed = mkt["v2-ed25519"]["B_ev"]
    exact = mkt["v3-manifest"]["B_ev"]
    sample = mkt["v3-policy-sample"]["B_ev"]
    bls = mkt["v2-bls"]["B_ev"]
    att = mkt["v4-attested"]["B_ev"]
    factor = cir[("attributed", 60)]["constraints"] / cir[("mean", 60)]["constraints"]
    return rf"""% generated by artifact/scripts/make_tables.py -- do not edit
\begin{{table}}[t]
\caption{{Decision rules from the executable model. Byte comparisons use
$n={n}$ and exclude pre-provisioned $P$ and claimed $y$. The attestation row
is a cost model; all others are executed.}}
\label{{tab:costvec}}
\centering
\scriptsize
\setlength{{\tabcolsep}}{{2.2pt}}
\begin{{tabular}}{{@{{}}L{{2.5cm}}L{{4.2cm}}L{{4.8cm}}@{{}}}}
\toprule
Design choice & Finding & Decision implication \\
\midrule
Raw records vs. commitments & Raw cumulative V4 is {si(raw)} B; commitment-based
V2 is {si(ed)} B. & Recompute when records are shorter than commitments and
disclosure is acceptable. \\
Exact vs. sampled coverage & Exact V3 reuses the {si(exact)}-B V2 manifest;
$k=20$ sampling uses {si(sample)} B. & Sampling saves only at scale and accepts
an explicit false-acceptance bound. \\
Ed25519 vs. BLS & BLS reduces V2 to {si(bls)} B but uses 61 verifier pairings. &
Choose from auditor work and public-verification needs, not tag size alone. \\
Succinct attribution & In-circuit EdDSA expands the mean circuit {factor:.1f}$\times$. &
Keep authentication outside the circuit or choose proof-friendly credentials
when the trust model permits. \\
\emph{{Modeled:}} attestation & A root, external anchor, and report total {si(att)} B
under $\rho_{{\mathrm{{iso}}}}$. & Compare the isolated-path and appraisal
assumptions before comparing bytes. \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def circuit_table(sn):
    base = next(r for r in sn["results"] if r["circuit"] == "binding")["constraints"]
    rows = [
        ("binding", 60, "input binding", "manifest binding"),
        ("mean", 60, "+ arithmetic mean", "G4 arithmetic"),
        ("excursion", 60, "+ excursion count", "G4 comparison"),
        ("mkt", 60, "+ bounded MKT", "G4 approximation"),
        ("attributed", 60, "+ EdDSA attribution and mean", "G2--G4"),
    ]
    idx = {(r["circuit"], r["n"]): r for r in sn["results"]}
    lines = []
    for name, n, label, goals in rows:
        r = idx.get((name, n))
        if not r:
            continue
        reference = idx[("mean", 60)]["constraints"] if name == "attributed" else base
        added = "---" if name == "binding" else si(r["constraints"] - reference)
        lines.append(" & ".join([
            label, si(r["constraints"]),
            ("+" + added if added != "---" else added), goals,
        ]) + r" \\")
    body = "\n".join(lines)
    return rf"""% generated by artifact/scripts/make_tables.py -- do not edit
\begin{{table}}[t]
\caption{{Constraint waterfall at $n=60$. Operator rows are alternatives over
the binding layer; attribution is added to the arithmetic mean. The attributed
row was compiled but not proven at $n=60$ and still requires external G1.}}
\label{{tab:circuits}}
\centering
\small
\setlength{{\tabcolsep}}{{4pt}}
\begin{{tabular}}{{@{{}}lrrl@{{}}}}
\toprule
Layer & Constraints & Increment & Direct role \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


if __name__ == "__main__":
    data = json.load(open("results/stacks.json"))
    sn = json.load(open("results/snark.json"))
    (OUT / "costvec.tex").write_text(cost_table(data, sn))
    (OUT / "circuits.tex").write_text(circuit_table(sn))
    print("wrote", [p.name for p in sorted(OUT.glob("*.tex"))])
